version: "3"
services:
#  api:
#    container_name: backend
#    hostname: backend
#    depends_on:
#      - elasticsearch
#    build: ./
#    restart: always
#    ports:
#      - "8080:8080"
  elasticsearch:
    hostname: elastic
    image: elasticsearch:7.17.6
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es-net
  kibana:
    image: kibana:7.17.13
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - es-net
  postgres:
    hostname: postgres
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local

networks:
  es-net: